### ISSUE TITLE
Invalid parameter type passed to `BuckarooSoap::_error()`

### ISSUE THREAD

**Issue by fiechtor** [buckaroo-it/WooCommerce#194]
Got the following error:

```
Uncaught Error: Call to undefined method SoapFault::__getLastResponse() 
in /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/soap.php:362 
Stack trace:
#0 /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/soap.php(47): BuckarooSoap->_error()
#1 /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/paymentmethods/paymentmethod.php(434): BuckarooSoap->transactionRequest()
#2 /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/paymentmethods/paymentmethod.php(447): BuckarooPaymentMethod->executeRequestOfType()
#3 /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/paymentmethods/paymentmethod.php(408): BuckarooPaymentMethod->PayGlobal()
#4 /.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/paymentmethods/ideal/ideal.php(30): BuckarooPaymentMethod->Pay()
#5 /.../web/app/plugins/wc-buckaroo-bpe-gateway/gateway-buckaroo-ideal.php(74): BuckarooIDeal->Pay()
#6 /.../web/app/plugins/woocommerce/includes/class-wc-form-handler.php(449): WC_Gateway_Buckaroo_Ideal->process_payment()
#7 /.../web/wp/wp-includes/class-wp-hook.php(310): WC_Form_Handler::pay_action()
#8 /.../web/wp/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#9 /.../web/wp/wp-includes/plugin.php(565): WP_Hook->do_action()
#10 /.../web/wp/wp-includes/class-wp.php(796): do_action_ref_array()
#11 /.../web/wp/wp-includes/functions.php(1335): WP->main()
#12 /.../web/wp/wp-blog-header.php(16): wp()
#13 /.../web/index.php(6): require('...')
#14 {main} thrown"
file: "/.../web/app/plugins/wc-buckaroo-bpe-gateway/library/api/soap.php"
```

Cause by
https://github.com/buckaroo-it/WooCommerce/blob/90ab2efc101900e99e7a2cde429bc53ae8a120c1/library/api/soap.php#L45-L48

Where `SoapClient::_error()` should only accept `SoapClient|false`.

**Comment by Buckaroo-Rene** [comment]
@fiechtor ,
A big thank you for your help in fixing that issue.
The fix is merged and it's set for our next release. We truly value your contributions.
