### ISSUE TITLE
BP-3640 Uncaught TypeError: number_format(): Argument #1 ($num) must be of type float, string given in ...

### ISSUE THREAD

**Issue by wallem89** [buckaroo-it/WooCommerce#272]
I receive this automated message of WordPress that this plugin has an issue. Although I don't see that any payment is failing.

Stack trace (with domain name replaced by `{MY_DOMAIN_NAME}`):
```
#0 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-content/plugins/wc-buckaroo-bpe-gateway/library/common.php(833): number_format('', 2, '.', '')
#1 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-content/plugins/wc-buckaroo-bpe-gateway/includes/admin/meta-boxes/views/html-order-shipping.php(96): roundAmount('')
#2 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-content/plugins/wc-buckaroo-bpe-gateway/includes/admin/meta-boxes/views/html-order-capture.php(178): include('/data/sites/web...')
#3 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-content/plugins/wc-buckaroo-bpe-gateway/includes/admin/meta-boxes/class-wc-meta-box-order-capture.php(32): include('/data/sites/web...')
#4 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-admin/includes/template.php(1456): BK_Meta_Box_Order_Items::output(Object(WP_Post), Array)
#5 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-admin/edit-form-advanced.php(723): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#6 /data/sites/web/{MY_DOMAIN_NAME}/www/wp-admin/post.php(206): require('/data/sites/web...')
#7 {main}
  thrown
```

WordPress version `6.5.5`
Theme: bootCommerce Child (version `5.2.0.0`)
Plugin: WC Buckaroo BPE Gateway (version `3.13.1`)
PHP version ` 8.1.29`

**Comment by Buckaroo-Rene** [comment]
Hi @wallem89 ,

Thanks for informing us about this issue.
Our development team will take a look at it.
Will let you know when we have a update regarding this issue.

Best regards,
René

**Comment by Buckaroo-Rene** [comment]
Released in https://github.com/buckaroo-it/WooCommerce/releases/tag/v3.14.0
